[libdefaults]
  default_realm = GROUPCLAES.BE
  dns_lookup_realm = true
  dns_lookup_kdc = true
  dns_canonicalize_hostname = false
  rdns = false

[realms]
  GROUPCLAES.BE = {
    kdc = hodor.groupclaes.be
  }
